### ISSUE TITLE
Android gives exception after getting the request

### ISSUE THREAD

**Issue by ebatuhankaynak** [NinoApp/nino-client#3]
D/ATTEMPTING: TEXT: text: • Bu kart ipinde mikrogip ve anten bulunan bir akilli karttir (smart x: 0.38823529411764707 y: 0.2773370127630217 r: 2079.0 mW: 0.9066666666666667
D/ATTEMPTING: TEXT: text: card). Karti okuyucu cihaza 5-6 cm kadar yakla^tirmak yeterlidir x: 0.7058823529411764 y: 0.3601241807519834 r: 2111.0 mW: 0.8533333333333334
    text: • Karti giine^te birakmayiniz, kivirmaymiz ve egip bukmeyiniz x: 0.3941176470588235 y: 0.4470507071403932 r: 1981.0 mW: 0.8133333333333334
D/ATTEMPTING: TEXT: text: • Ogrencinin universiteden ayrilmasi durumunda, kart Ogrenci x: 0.40588235294117647 y: 0.5608830631252155 r: 1989.0 mW: 0.8
    text: i^leri Mudurlugu’ne iade edilmelidir x: 0.6941176470588235 y: 0.6271127975163848 r: 1161.0 mW: 0.48000000000000004
    text: • Kartu gegerlilik suresi on yuze yapi§tirilmi§ holografik puld. x: 0.4117647058823529 y: 0.727492238703001 r: 1936.0 mW: 0.8533333333333334
W/System: A resource failed to call close. 
W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
W/System.err: java.io.FileNotFoundException: No package found for authority: android.resource://com.nino.ninoclient/drawable/bbg
        at android.content.ContentResolver.getResourceId(ContentResolver.java:1541)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1005)
        at ly.img.android.pesdk.backend.decoder.Decoder.getUncachedInputStream(Decoder.java:168)
        at ly.img.android.pesdk.backend.decoder.Decoder.getInputStream(Decoder.java:232)
        at ly.img.android.pesdk.backend.model.state.EditorLoadSettings.loadImageInfo(EditorLoadSettings.java:218)
        at ly.img.android.serializer._3._0._0.PESDKFileReader.loadImageInfo(PESDKFileReader.java:130)
        at ly.img.android.serializer._3._0._0.PESDKFileReader.parseFile(PESDKFileReader.java:117)
        at ly.img.android.serializer._3._0._0.PESDKFileReader.readJson(PESDKFileReader.java:107)
        at com.maubis.scarlet.base.nino.PhotoEditorActivity.openEditor(PhotoEditorActivity.java:248)
        at com.maubis.scarlet.base.nino.PhotoEditorActivity.requestPermissionAndOpenEditor(PhotoEditorActivity.java:181)
W/System.err:     at com.maubis.scarlet.base.nino.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:153)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=CameraActivity, firebase_previous_id(_pi)=7906508856623494600, firebase_screen_class(_sc)=PhotoEditorActivity, firebase_screen_id(_si)=7906508856623494601}]
I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
    Activity resumed, time: 353383900
E/RecyclerView: No adapter attached; skipping layout
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 44
    Connection attempt already in progress
V/FA: Activity paused, time: 353383943
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@860eba
V/FA: onActivityCreated
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bijoysingh.quicknote.pro, PID: 4673
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bijoysingh.quicknote.pro/ly.img.android.pesdk.ui.activity.PhotoEditorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int ly.img.android.pesdk.backend.model.state.manager.StateHandler.findId(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2919)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int ly.img.android.pesdk.backend.model.state.manager.StateHandler.findId(java.lang.String)' on a null object reference
        at ly.img.android.events.$EventSet.findId($EventSet.java:9)
        at ly.img.android.pesdk.backend.model.state.$EditorLoadSettings_EventAccessor.add($EditorLoadSettings_EventAccessor.java:13)
        at com.maubis.scarlet.base.PESDKEvents.register(PESDKEvents.java:59)
        at ly.img.android.pesdk.backend.model.state.manager.StateHandler.registerSettingsEventListener(StateHandler.java:286)
        at ly.img.android.pesdk.backend.model.state.manager.StateObservable.onBind(StateObservable.java:70)
        at ly.img.android.pesdk.backend.model.state.manager.StateHandler.<init>(StateHandler.java:104)
        at ly.img.android.pesdk.ui.activity.ImgLyActivity.getStateHandler(ImgLyActivity.java:95)
        at ly.img.android.pesdk.ui.activity.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:280) 
        at android.app.ActivityThread.main(ActivityThread.java:6706) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 4673 SIG: 9
Application terminated.

**Comment by ebatuhankaynak** [comment]
Fixed the path to black background bbg.jpg, the error is updated to be:

D/ATTEMPTING: TEXT: text: Bu kart \p\nde m\krop\p ve anten bulunan bir akilli karttir (smart x: 0.4001721170395869 y: 0.2761025254428948 r: 2161.0 mW: 0.88
    text: card). Kart\ okuyucu cihaza 5-6 cm kadar yakla^tirmak yeterlidir x: 0.46901893287435453 y: 0.3580851865812288 r: 2193.0 mW: 0.8533333333333334
    text: Kart\ gune^te btrakmaytniz, kivirmayiniz ve egip bukmeyiniz x: 0.5507745266781411 y: 0.44477949491142105 r: 2080.0 mW: 0.7866666666666667
D/ATTEMPTING: TEXT: text: Ogrenc\n\n unwersiteden aynlmasi durumunda, kart Ogrenci x: 0.6067125645438898 y: 0.554089709762533 r: 2094.0 mW: 0.7466666666666667
    text: \^\er\ Mudurtugu'ne lade edilmelidir x: 0.6626506024096385 y: 0.6323030531473803 r: 1306.0 mW: 0.48000000000000004
    text: op^.^rUWk suresi bn yuze yapi§tirilmi§ holografik pukl; x: 1.7469879518072287 y: 0.6813041839427064 r: 2080.0 mW: 0.7333333333333334
D/ATTEMPTING: TEXT: text: car x: 0.46901893287435453 y: 0.341123256690539 r: 220.0 mW: 0.04
    text: i • Ka x: 0.0 y: 0.4334715416509612 r: 225.0 mW: 0.08
    text: \.Oc x: 0.02581755593803786 y: 0.5974368639276291 r: 228.0 mW: 0.05333333333333334
    text: H * x: 0.06884681583476764 y: 0.6813041839427064 r: 230.0 mW: 0.04
W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
V/ExifParser: Reading exif...
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=CameraActivity, firebase_previous_id(_pi)=-6907056873920043480, firebase_screen_class(_sc)=PhotoEditorActivity, firebase_screen_id(_si)=-6907056873920043479}]
I/Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
    Activity resumed, time: 356925483
E/RecyclerView: No adapter attached; skipping layout
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 36
    Connection attempt already in progress
    Activity paused, time: 356925519
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8aa52e3
V/FA: onActivityCreated
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bijoysingh.quicknote.pro, PID: 15743
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bijoysingh.quicknote.pro/ly.img.android.pesdk.ui.activity.PhotoEditorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int ly.img.android.pesdk.backend.model.state.manager.StateHandler.findId(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2919)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int ly.img.android.pesdk.backend.model.state.manager.StateHandler.findId(java.lang.String)' on a null object reference
        at ly.img.android.events.$EventSet.findId($EventSet.java:9)
        at ly.img.android.pesdk.backend.model.state.$LayerListSettings_EventAccessor.add($LayerListSettings_EventAccessor.java:12)
        at com.maubis.scarlet.base.PESDKEvents.register(PESDKEvents.java:59)
        at ly.img.android.pesdk.backend.model.state.manager.StateHandler.registerSettingsEventListener(StateHandler.java:286)
        at ly.img.android.pesdk.backend.model.state.manager.StateObservable.onBind(StateObservable.java:70)
        at ly.img.android.pesdk.backend.model.state.LayerListSettings.onBind(LayerListSettings.java:134)
        at ly.img.android.pesdk.backend.model.state.manager.StateHandler.<init>(StateHandler.java:104)
        at ly.img.android.pesdk.ui.activity.ImgLyActivity.getStateHandler(ImgLyActivity.java:95)
        at ly.img.android.pesdk.ui.activity.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:280) 
        at android.app.ActivityThread.main(ActivityThread.java:6706) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 15743 SIG: 9
Application terminated.

**Comment by ebatuhankaynak** [comment]
Fixed in 6e45085313dbcdfa0445365756f6372e2d3cacaf
